name: UI Tests Against Nuvio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout QA repo
      - name: Checkout QA repo
        uses: actions/checkout@v4
        with:
          path: NuvioQAUT

      # Checkout Nuvio repo
      - name: Checkout Nuvio
        uses: actions/checkout@v4
        with:
          repository: leonardo381/Nuvio
          path: Nuvio

      # Install Go (needed to run Nuvio)
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      # Start Nuvio
      - name: Start Nuvio
        working-directory: Nuvio
        run: |
          nohup go run ./examples/base serve > nuvio.log 2>&1 &
          sleep 10

      # Setup .NET for Playwright tests
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      # Build test project
      - name: Restore tests
        working-directory: NuvioQAUT/PlaywrightBDD
        run: dotnet restore

      - name: Build tests
        working-directory: NuvioQAUT/PlaywrightBDD
        run: dotnet build --configuration Debug

      # Install Playwright browsers
      - name: Install Playwright
        working-directory: NuvioQAUT/PlaywrightBDD
        run: pwsh bin/Debug/net9.0/playwright.ps1 install --with-deps

      # Prepare artifact folders
      - name: Prepare artifact folders
        working-directory: NuvioQAUT/PlaywrightBDD
        run: |
          mkdir -p artifacts/traces
          mkdir -p artifacts/screenshots

      # Run UI tests
      - name: Run UI tests
        working-directory: NuvioQAUT/PlaywrightBDD
        env:
          BASE_URL: http://127.0.0.1:8090
          HEADLESS: true
          ADMIN_USER: ${{ secrets.ADMIN_USER }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          TRACING: true
          SCREENSHOT_ON_FAILURE: true
          ARTIFACT_DIR: artifacts
        run: dotnet test --filter "Category=UI"

      - name: Debug artifact files
        if: always()
        working-directory: NuvioQAUT/PlaywrightBDD
        run: |
          pwd
          find artifacts -maxdepth 5 -type f | sort || true

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: NuvioQAUT/PlaywrightBDD/artifacts/**